### ISSUE TITLE
Is this the best template for browser

### ISSUE THREAD

**Issue by simonpfrank** [robocorp/template-python-browser#4]
Apologies, going to debate. As an example of a bot which uses javascript to do something perhaps it is OK, but this bypasses using standard Playwright methods such as locator and all the get_by_* methods. As this appears whenever you start a browser template, I am not sure it is a good best practise template that shows the benefits of the library.

Perhaps building one just using Playwrite methods would be better ?

**Comment by cmin764** [comment]
This is the currently recommended browser template for now, as this is showcasing how to automate a tedious form filling process from start to finish, including any other web-related resources like the downloaded input Excel file through the 3rd-party `requests` library. In terms of locating elements, we decided to go on with the `.locator()` method (and its wrappers), so you'd have more freedom & flexibility in strategy by just changing the selector string value itself. This way the code gets a more generic shape and focuses more on the "meat" rather than the infrastructure. (and it is proved to go well with our AI chatbot, [ReMark](https://chat.robocorp.com/), as well)

On top of this, we reveal a simple native setup/teardown mechanism along with imports sorting, constants declaring, docstrings standard and Python code formatting. Through the multiple functions defined, we display the separation of concerns for an improved maintenance.

As we’re open for debates, can you please suggest a more appropriate template? It can reach our [Portal](https://robocorp.com/portal) as an example to be used by others as well.

Will close this for now, please re-open if you're not satisfied with the answer and if you wish to contribute, thank you!
